In [2]:
import torch

In [8]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [9]:
A.T

tensor([[ 0.,  4.,  8., 12., 16.],
        [ 1.,  5.,  9., 13., 17.],
        [ 2.,  6., 10., 14., 18.],
        [ 3.,  7., 11., 15., 19.]])

In [10]:
B = A.clone()
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [11]:
# element should be float if want to compute mean
A.mean()

tensor(9.5000)

In [14]:
# dot product
B = torch.ones(4,3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [15]:
# compute F norm
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [16]:
# compute L1 norm
torch.abs(u).sum()

tensor(7.)