In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

Compute derivative for y=2xTx

In [2]:
# save gradient
x.requires_grad_(True)   # equals to x = torch.arange(4.0, requires_grad=True)
x.grad 

In [4]:
# compute y
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
# use backward propagation to compute gradient of y respect to x
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
# by default, pytorch automatically accumulate gradient
# we need to get rid of previous value
x.grad.zero_()  # clear previous gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [7]:
x.grad.zero_()
y = x * x
u = y.detach()  # no longer consider x as a variable
z = u * x       # only consider x * x as a constant

z.sum().backward()
x.grad == u

tensor([True, True, True, True])